logo=default
updating_visualizer=yes

modules={
    hostname
    spacer
    os
    kernel
    spacer
    uptime
    spacer
    cpu
    spacer
    memory
    swap
    disk
    spacer
    local_ip
    locale
}